version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=Son[1122002]
      - POSTGRES_DB=smart_ricebox_db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: