"""empty message

Revision ID: 012d73222bc1
Revises: 17abf2058d11
Create Date: 2023-09-21 10:46:10.015273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012d73222bc1'
down_revision: Union[str, None] = '17abf2058d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ricebox',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('house_num_street', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('alarm_rice_threshold', sa.Integer(), nullable=False),
    sa.Column('current_rice_amount', sa.Integer(), nullable=True),
    sa.Column('current_humidity', sa.Integer(), nullable=True),
    sa.Column('current_temperature', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ricebox')
    # ### end Alembic commands ###
