"""Remove username

Revision ID: 0296c2b4cfc1
Revises: 1b2257fd0c5e
Create Date: 2023-08-21 14:49:18.520652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0296c2b4cfc1'
down_revision: Union[str, None] = '1b2257fd0c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_name_key', 'users', type_='unique')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_user_name_key', 'users', ['user_name'])
    # ### end Alembic commands ###
