"""empty message

Revision ID: 19f1357d473e
Revises: d1753b0d75b1
Create Date: 2023-09-21 10:30:32.416900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f1357d473e'
down_revision: Union[str, None] = 'd1753b0d75b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ricebox', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('ricebox', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ricebox', 'latitude')
    op.drop_column('ricebox', 'longitude')
    # ### end Alembic commands ###
