"""add dashboard url RiceBox entity

Revision ID: 358e6be2eb98
Revises: 012d73222bc1
Create Date: 2023-09-21 20:35:29.696313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358e6be2eb98'
down_revision: Union[str, None] = '012d73222bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ricebox', sa.Column('url_dashboard', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ricebox', 'url_dashboard')
    # ### end Alembic commands ###
