"""empty message

Revision ID: 3ad7992cd9a4
Revises: 7225fc20c005
Create Date: 2023-09-25 02:59:29.093030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad7992cd9a4'
down_revision: Union[str, None] = '7225fc20c005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ricebox', sa.Column('tick_deliver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ricebox', 'tick_deliver')
    # ### end Alembic commands ###
