"""empty message

Revision ID: 674e28245589
Revises: 56fb79f1c7c5
Create Date: 2023-09-22 11:10:41.826147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674e28245589'
down_revision: Union[str, None] = '56fb79f1c7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ricebox_name_key', 'ricebox', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ricebox_name_key', 'ricebox', ['name'])
    # ### end Alembic commands ###
