"""empty message

Revision ID: 7225fc20c005
Revises: 65eacc867903
Create Date: 2023-09-23 15:07:53.864264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7225fc20c005'
down_revision: Union[str, None] = '65eacc867903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ricebox', sa.Column('have_buy_rice_request', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ricebox', 'have_buy_rice_request')
    # ### end Alembic commands ###
