"""Added owner_id RiceBox

Revision ID: adea823a9251
Revises: 0296c2b4cfc1
Create Date: 2023-09-02 16:23:32.347683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adea823a9251'
down_revision: Union[str, None] = '0296c2b4cfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ricebox', sa.Column('city', sa.String(length=20), nullable=False))
    op.add_column('ricebox', sa.Column('owner_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'ricebox', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ricebox', type_='foreignkey')
    op.drop_column('ricebox', 'owner_id')
    op.drop_column('ricebox', 'city')
    # ### end Alembic commands ###
