"""Update RiceBox Entiti

Revision ID: d1753b0d75b1
Revises: adea823a9251
Create Date: 2023-09-16 13:23:12.402713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1753b0d75b1'
down_revision: Union[str, None] = 'adea823a9251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ricebox', sa.Column('current_rice_amount', sa.Integer(), nullable=True))
    op.add_column('ricebox', sa.Column('current_humidity', sa.Integer(), nullable=True))
    op.add_column('ricebox', sa.Column('current_temperature', sa.Integer(), nullable=True))
    op.alter_column('ricebox', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ricebox', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('ricebox', 'current_temperature')
    op.drop_column('ricebox', 'current_humidity')
    op.drop_column('ricebox', 'current_rice_amount')
    # ### end Alembic commands ###
