"""add dashboard url RiceBox entity

Revision ID: fd65d6c66eb1
Revises: 358e6be2eb98
Create Date: 2023-09-21 20:40:21.309364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd65d6c66eb1'
down_revision: Union[str, None] = '358e6be2eb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
